config/routes.rb
Rails.application.routes.draw do
  devise_for :custumers
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
  get 'signup',to: 'users#new'
  resources :users,except: [:new]
  root 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title,presence: true,length: {minimum:4,maximum:100}
  validates :description,presence: true,length: {minimum:4,maximum:300}
  belongs_to :user
end

app/models/custumer.rb
class Custumer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :articles
  validates :username,presence: true, uniqueness: {case_sensitive: false},length: { minimum:4,maximum:100 }
  validates :email,presence: true,uniqueness: {case_sensitive: false},length: { maximum:105 },format: {with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/i}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#before_action :authenticate_custumer!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show,:edit,:update,:destroy]
  def show
    #byebug
    #@article = Article.find(params[:id])
  end
  def index
    @articles = Article.all
  end
  def new
    @article = Article.new
  end
  def edit
    #@article = Article.find(params[:id])
  end
  def create
    @article = Article.new(article_params)#params.require(:article).permit(:title, :description))
    @article.user = User.first
    if @article.save
      flash[:notice] = "Article was created successfully"
      redirect_to @article
    else
      render 'new'
    end
  end
  def update
    #@article = Article.find(params[:id])
    if @article.update(article_params)#params.require(:article).permit(:title, :description))
      flash[:notice] = "Article was updated succesfully"
      redirect_to @article
    else
      render 'edit'
    end
  end
  def destroy
    #@article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
  private
  def set_article
    @article = Article.find(params[:id])
  end
  def article_params
    params.require(:article).permit(:title, :description, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController <ApplicationController
  def about
   @a=current_user.articles
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @articles = @user.articles
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
       if @user.save
         format.html { redirect_to user_url(@user), notice: "User was successfully created." }
         format.json { render :show, status: :created, location: @user }
       else
         format.html { render :new, status: :unprocessable_entity }
         format.json { render json: @user.errors, status: :unprocessable_entity }
       end
     end
  end

  # PATCH/PUT /users/1 or /users/1.json
   def update
     respond_to do |format|
       if @user.update(user_params)
         format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
         format.json { render :show, status: :ok, location: @user }
       else
         format.html { render :edit, status: :unprocessable_entity }
         format.json { render json: @user.errors, status: :unprocessable_entity }
       end
     end
   end

  # DELETE /users/1 or /users/1.json
   def destroy
     @user.destroy

     respond_to do |format|
       format.html { redirect_to users_url, notice: "User was successfully destroyed." }
       format.json { head :no_content }
     end
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<h1>Articles listing pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User_id</th>
      <th colspan = "3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <td><%= article.user_id %></td>
      <td><%= link_to 'Show',article_path(article) %></td>
      <td><%= link_to 'Edit',edit_article_path(article) %></td>
      <td><%= link_to 'Delete',article_path(article),method: :delete,data: {confirm:"Are you sure?"} %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<p>
  <%= link_to 'create new article',new_article_path %>
</p>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @article,local: true) do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :user_id %><br/>
    <%= f.text_field :user_id %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<%= render 'form' %>

<%= link_to 'Cancel and Return to articles listing',articles_path %>

app/views/articles/index.html.erb
<h1>Articles listing pages</h1>
<%= render 'article' %>

app/views/articles/new.html.erb
<h1>Create a new article</h1>
<%= render 'form' %>

<%= link_to 'Return to articles listing',articles_path %>

app/views/articles/show.html.erb
<h1>showing article details</h1>
<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>
<p><strong>User_id: </strong><%= @article.user_id %></p>
<%= link_to 'Edit',edit_article_path(@article) %>|
<%= link_to 'Delete',article_path(@article),method: :delete,data: {confirm: "Are you sure?"} %>|
<%= link_to 'Return to articles listing',articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if custumer_signed_in? %>
     <%= link_to 'logout',destroy_custumer_session_path ,method: :delete %>
     <% else %>
     <%= link_to 'login',new_custumer_session_path %>

    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
"iglfkdsxcvkjl"
<% @a.each do |a|%>
<%= a.title %>
<%= a.description %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.password_field :password_digest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <%= pluralize(user.articles.count,"article") %><br/>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'signup', signup_path %>

app/views/users/new.html.erb
<h1>SignUp for practice</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Password:</strong>
  <%= @user.password_digest %>
</p>
<h3>Articles</h3>
<%= render 'articles/article' %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>